### ISSUE TITLE
UTF-8 encoding issue in PHP files

### ISSUE THREAD

**Issue by odan** [welovecoding/editorconfig-netbeans#75] opened 2015-05-31 20:04 UTC
Hi, in my php unittest a have a string like:
<pre>'öäü#+!"§$%&/()=?´\\~<>|ÿ'</pre>

If I enable the editorconfig-netbeans plugin this string is converted to 
<pre>'ÃƒÂ¶ÃƒÂ¤ÃƒÂ¼#+!"Ã‚Â§$%&/()=?Ã‚Â´\\~<>|ÃƒÂ¿'</pre>

Here is my current .editorconfig
<pre>
root = true

[*]
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = false
indent_style = space
indent_size = 4
</pre>

editorconfig-netbeans Version: v0.0.7-beta
Java Version: 8

**Comment by bennyn** [comment] 2015-06-18 13:55
Hi @odan,

Thank you for your report! What's the original character set of your file? Looks like the EditorConfig converted it from something else than UTF-8 to UTF-8.

**Comment by odan** [comment] 2015-06-18 18:33
My default character is (always) UTF-8.

**Comment by retokohli** [comment] 2015-09-23 11:22
Hi @bennyn,
I can confirm the issue.  We use UTF-8 as the default encoding.
If the plugin is disabled, editing and saving files works as expected.
When the plugin is enabled, and a file is saved, all multibyte charactes apparently are treated as single byte characters and encoded to UTF-8 again, as described by @odan.
Please let me know if I can assist you further.

**Comment by odan** [comment] 2015-11-08 20:05
Hello

This issue still exist in v0.0.8.

My current workaround: 
Remove this line
```
charset = utf-8
```
and the original characters are not converted from UTF-8 to UTF-8.

*NetBeans v8.1*
*editorconfig-netbeans Version: v0.0.8*

**Comment by junichi11** [comment] 2015-11-08 22:30
@odan Hi, Can you provide a simple reproducible project?

**Comment by oroszlanyzsolt** [comment] 2015-11-09 14:21
In NetBeans 8.1 and editorconfig-0.0.8.nbm the problem still persist the project character set encoding is set to UTF-8. It does not matter if the charset = utf-8 is defined in .editorconfig or not characters like "éáű" became garbage after saving.
OS: Windows 7 x64 SP1

**Comment by junichi11** [comment] 2015-11-09 14:55
It would be helpful if you can provide a simple reproducible project (e.g. as public repo. on GitHub).

**Comment by oroszlanyzsolt** [comment] 2015-11-09 18:29
Okey I have naroved the problem down to trim_trailing_whitespace = true this little beast cause the éáűőúóüöíÉÁŰŐÚÓÜÖÍ become Ä‚Â©Ä‚Ë‡ÄąÂ±Äąâ€�Ä‚ĹźÄ‚Ĺ‚Ä‚Ä˝Ä‚Â¶Ä‚Â­Ä‚â€°Ä‚ďż˝ÄąÂ°Äąďż˝Ä‚ĹˇÄ‚â€śÄ‚Ĺ›Ä‚â€“Ä‚Ĺ¤.
trim_trailing_whitespace = true without end_of_line = lf the text becomes corrupted, if you enable end_of_line = lf again it is saved properly. Here you can test it: https://github.com/oroszlanyzsolt/editorconfig-netbeans-test

**Comment by junichi11** [comment] 2015-11-10 03:17
@oroszlanyzsolt Thanks for your information and providing your sample project!

@bennyn I'll fix this since probably I found the cause.

**Comment by oroszlanyzsolt** [comment] 2015-11-10 08:22
Awesome, thank you! Is it possible to read the character encoding from the project configuration file?

**Comment by junichi11** [comment] 2015-11-10 13:44
> Is it possible to read the character encoding from the project configuration file?

Probably, generally it is not possible because a project may not have its settings.

**Comment by oroszlanyzsolt** [comment] 2015-11-10 17:03
This sounds bad, at least Netbeans developers should allow access to project configuration at least some options would be available for plugin  developers.

**Comment by junichi11** [comment] 2015-11-11 02:34
Well... I meant there is no common api which can directly get an encoding from configurations of all project type. e.g. we can get it from a php project. But there are a few problems and It is not smart to get it per project type. So, instead, I used an api which can get it from a file. If `charset` is not set, it will be used. I added a new commit to the PR.

**Comment by bennyn** [comment] 2015-11-11 10:23
@oroszlanyzsolt Thanks for taking the time and reporting the encoding issue. We hope that it is fixed now with **v0.0.9**. 

You can download it here: 
https://github.com/welovecoding/editorconfig-netbeans/releases/tag/v0.0.9-beta

Can you please report back if your issue is fixed now?

**Comment by oroszlanyzsolt** [comment] 2015-11-11 17:43
Should I open a bug report or post it here because I found something else. The UTF-8 encoding issue in PHP files works flawlessly now.

**Comment by bennyn** [comment] 2015-11-11 18:00
If it is something new, then please open a new ticket. :)

**Comment by junichi11** [comment] 2015-11-13 02:15
Thanks for verification!

I think we can close this issue.

**Closed by junichi11** 2015-11-13 02:15 UTC
Labels: epic: Write File, flag: investigation, prio: high, type: bug

**Comment by bennyn** [comment] 2015-11-17 09:25
@junichi11 I know that this issue here is solved now but I have seen that some NetBeans projects have the following written in their `project.properties` file:

```ini
files.encoding=UTF-8
```

Do you think it might make sense to write / change this property (if possible)?

**Comment by junichi11** [comment] 2015-11-17 11:09
@bennyn Umm, perhaps yes... but I think that we should not write/change it because an API is not provided to do it.

**Comment by bennyn** [comment] 2015-11-17 11:31
Ok, thanks for your feedback!
