### ISSUE TITLE
Plugin triggers automatic reformat on save

### ISSUE THREAD

**Issue by m6w6** [welovecoding/editorconfig-netbeans#98] opened 2016-05-12 10:16 UTC
When the plugin is active, it triggers a complete reformat of the file saved, though the option "Editor -> On Save -> Reformat" is explicitly disabled.

**Comment by Mte90** [comment] 2016-05-20 11:11
so this is the plugin that generate this problem...
I have also on my configuration but now i can disabled and works without problems.

**Comment by emabrey** [comment] 2016-11-18 08:03
@m6w6 @Mte90 
Do you mean it triggers the Netbeans configured reformat settings configured via Options?

Or do you mean that the plugin automatically fixes files to be compliant with the editorconfig on save (which is intended behavior I think)? If it is this second meaning then this should really be a feature request and not a bug.

**Comment by m6w6** [comment] 2016-11-18 10:16
The former. I wouldn't dare complaining about intended behavior :)

**Comment by Mte90** [comment] 2016-11-18 11:01
Yes, the reformat is executed at the save for every file and there is no option to disable it.

**Comment by emabrey** [comment] 2016-11-20 21:12
@m6w6 I have tried to figure out how and or why this might be happening simply by looking at the code but so far I can't figure it out. Can you give me some steps to reproduce?

**Comment by emabrey** [comment] 2016-11-20 21:35
@Mte90 Configuring editorconfig outside of the _.editorconfig_ file would be counterproductive (one of the great things about editorconfig is the file-based config). However, have you tried simply adding a section to the relevant _.editorconfig_ file which defines no style for the files in question? For example, to stop your mchammer files from being formatted:
```
[*.mchammer]
#Dont touch this
```
 The [supported wildcards for sections](http://editorconfig.org/#wildcards) is fairly robust, though as a last resort you could simply define a non-root _.editorconfig_ file in a child directory.

**Comment by bennyn** [comment] 2016-11-21 09:32
The automatic reformat is triggered by [these lines of code](https://github.com/welovecoding/editorconfig-netbeans/blob/master/src/main/java/com/welovecoding/nbeditorconfig/io/writer/StyledDocumentWriter.java#L160-L161):

```java
Reformat reformat = Reformat.get(cookie.getDocument());
reformat.lock();
try {
  reformat.reformat(0, cookie.getDocument().getLength());
} catch (BadLocationException ex) {
  LOG.log(Level.SEVERE, "AutoFormat on document not possible: {0}", ex.getMessage());
} finally {
  reformat.unlock();
  // Save document after reformat
  cookie.saveDocument();
}
```

When an [EditorConfig](http://editorconfig.org/) file is found, we update the properties on the [Project Formatting](https://blogs.oracle.com/coreqa/entry/formatting_settings_per_project). To do the actual formatting, we use NetBean's internal `Reformat` class which applies all formatting settings specified (which might be more than what EditorConfig defines).

If we know how to programmatically check if "Editor -> On Save -> Reformat" is disabled, then we could add an `if... else...` around this reformat block.

@junichi11, do you know how to programmatically check for the "Reformat" option in NetBeans?

**Screenshot of global Reformat option:**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/20477407/c2d333f0-afd5-11e6-8eaa-337e7488cc26.PNG)

**Comment by emabrey** [comment] 2016-11-21 11:53
The `ReformatOnSaveTask` class (within the org-netbeans-modules-editor module) is the class the IDE uses to reformat files on save. It checks for the reformat settings by using the `SimpleNameValue.ON_SAVE_REFORMAT` key to query a `Preferences` instance created based upon the queried value of `SimpleNameValue.ON_SAVE_USE_GLOBAL_SETTINGS`. The `SimpleNameValue.ON_SAVE_REFORMAT` key can return [multiple values](http://grepcode.com/file/bits.netbeans.org/maven2/org.netbeans.api/org-netbeans-modules-editor-settings/RELEASE80/org/netbeans/api/editor/settings/SimpleValueNames.java#SimpleValueNames.0ON_SAVE_REFORMAT) which indicate if/what reformatting is appropriate. [View the code I am referencing here.](http://grepcode.com/file/bits.netbeans.org/maven2/org.netbeans.api/org-netbeans-modules-editor/RELEASE80/org/netbeans/modules/editor/impl/ReformatBeforeSaveTask.java#108)

**Comment by junichi11** [comment] 2016-11-21 12:09
> It checks for the reformat settings by using the SimpleNameValue.ON_SAVE_REFORMAT key to query a Preferences instance created based upon the queried value of SimpleNameValue.ON_SAVE_USE_GLOBAL_SETTINGS. The SimpleNameValue.ON_SAVE_REFORMAT key can return multiple values which indicate if/what reformatting is appropriate. View the code I am referencing here.

@bennyn Probably, these can be used to check it.

**Comment by Mte90** [comment] 2017-10-06 21:01
any news for this one?

**Comment by Chris2011** [comment] 2017-11-01 19:23
I really want to contribute, but when I build it for NetBeans 8.2 and run it and open a project, I got lots of NoClassDefFound exceptions:

```
java.lang.NoClassDefFoundError: com/welovecoding/nbeditorconfig/listener/ProjectOpenCloseListener
	at com.welovecoding.nbeditorconfig.listener.ProjectHookLookup.createAdditionalLookup(ProjectHookLookup.java:53)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.doDelegate(DelegatingLookupImpl.java:139)
	at org.netbeans.spi.project.support.DelegatingLookupImpl.<init>(DelegatingLookupImpl.java:91)
	at org.netbeans.spi.project.support.LookupProviderSupport.createCompositeLookup(LookupProviderSupport.java:95)
	at org.netbeans.modules.web.clientproject.ClientSideProject.createLookup(ClientSideProject.java:585)
	at org.netbeans.modules.web.clientproject.ClientSideProject.<init>(ClientSideProject.java:231)
	at org.netbeans.modules.web.clientproject.ant.AntServices.factory(AntServices.java:178)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:128)
Caused: java.lang.IllegalArgumentException
	at org.netbeans.modules.project.ant.AntBasedGenericType.createProject(AntBasedGenericType.java:140)
	at org.netbeans.modules.project.ant.AntBasedProjectFactorySingleton.loadProject(AntBasedProjectFactorySingleton.java:264)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.createProject(NbProjectManager.java:401)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.access$300(NbProjectManager.java:94)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:314)
	at org.netbeans.modules.projectapi.nb.NbProjectManager$2.run(NbProjectManager.java:243)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.readAccess(DefaultMutexImplementation.java:209)
	at org.openide.util.Mutex.readAccess(Mutex.java:250)
	at org.netbeans.modules.projectapi.nb.NbProjectManager.findProject(NbProjectManager.java:243)
	at org.netbeans.api.project.ProjectManager.findProject(ProjectManager.java:167)
	at org.netbeans.modules.projectapi.SimpleFileOwnerQueryImplementation.getOwner(SimpleFileOwnerQueryImplementation.java:161)
	at org.netbeans.api.project.FileOwnerQuery.getOwner(FileOwnerQuery.java:116)
	at org.netbeans.modules.csl.core.ProjectClassPathProvider.findClassPath(ProjectClassPathProvider.java:66)
	at org.netbeans.api.java.classpath.ClassPath.getClassPath(ClassPath.java:676)
	at org.netbeans.modules.parsing.impl.indexing.errors.Utilities.getSourceClassPathFor(Utilities.java:86)
	at org.netbeans.modules.parsing.ui.indexing.errors.ErrorAnnotator$1.run(ErrorAnnotator.java:313)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor$Task.schedule(RequestProcessor.java:1484)
	at org.netbeans.modules.parsing.ui.indexing.errors.ErrorAnnotator.enqueue(ErrorAnnotator.java:255)
	at org.netbeans.modules.parsing.ui.indexing.errors.ErrorAnnotator.isInError(ErrorAnnotator.java:278)
	at org.netbeans.modules.parsing.ui.indexing.errors.ErrorAnnotator.annotateIcon(ErrorAnnotator.java:135)
	at org.netbeans.modules.masterfs.ui.FileBasedFSWithUI$UiDecorator.annotateIcon(FileBasedFSWithUI.java:77)
	at org.openide.loaders.DataFolder$FolderNode.getIcon(DataFolder.java:1250)
	at org.openide.nodes.FilterNode.getIcon(FilterNode.java:564)
	at org.openide.nodes.FilterNode.getIcon(FilterNode.java:564)
	at org.netbeans.modules.project.ui.PhysicalView$ProjectIconNode.getIcon(PhysicalView.java:426)
	at org.openide.nodes.FilterNode.getIcon(FilterNode.java:564)
	at org.netbeans.modules.project.ui.ProjectsRootNode$BadgingNode.getIcon(ProjectsRootNode.java:931)
	at org.netbeans.modules.project.ui.ProjectsRootNode$BadgingNode.getIcon(ProjectsRootNode.java:925)
	at org.openide.explorer.view.VisualizerNode.getIcon(VisualizerNode.java:558)
	at org.openide.explorer.view.NodeRenderer.configureFrom(NodeRenderer.java:238)
	at org.openide.explorer.view.NodeRenderer.getTreeCellRendererComponent(NodeRenderer.java:163)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
	at javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:553)
	at javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:199)
	at javax.swing.tree.AbstractLayoutCache.getPreferredWidth(AbstractLayoutCache.java:232)
	at javax.swing.plaf.basic.BasicTreeUI.updateCachedPreferredSize(BasicTreeUI.java:1897)
	at javax.swing.plaf.basic.BasicTreeUI.getPreferredSize(BasicTreeUI.java:2003)
	at javax.swing.plaf.basic.BasicTreeUI.getPreferredSize(BasicTreeUI.java:1991)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at org.openide.explorer.view.TreeView$ExplorerScrollPaneLayout.layoutContainer(TreeView.java:1709)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at org.netbeans.core.windows.view.ui.DesktopImpl$LayeredLayout.layoutContainer(DesktopImpl.java:554)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Chris2011** [comment] 2017-11-01 19:25
@bennyn so would be great if you can fix this error first and I can check the original problem of this ticket here. :)

**Comment by markiewb** [comment] 2017-11-05 01:37
@Chris2011: The issue reported by you (NoClassDefFoundError) is a duplicate of #103

**Comment by Chris2011** [comment] 2017-11-05 12:30
@markiewb ok thx.

**Comment by argordmel** [comment] 2017-11-08 16:10
I've the same problem, the editor reformat all lines when I save the file and I have disabled this option

Plugin Version: 0.10.2 
Netbeans 8.2
MacOS High Sierra

Thanks!

**Comment by Chris2011** [comment] 2017-11-08 16:11
@argordmel I created a PR #108 it is up to @bennyn :)

**Comment by bennyn** [comment] 2017-11-08 16:57
@Chris2011 I reviewed your code. Looks almost perfect, so we can merge it very soon. :)

**Closed** 2017-11-08 17:07 UTC
Labels: type: bug
