### ISSUE TITLE
git corruption after install

### ISSUE THREAD

**Issue by t3dev** [welovecoding/editorconfig-netbeans#76] opened 2015-06-03 10:41 UTC
Hi,

after adding the editorconfig-netbeans plugin into my netbeans I created a HTML5-project with existing source. The sources had an .editorconfig and a .git directory already.

Afterwards I noticed a problem with git on the shell:

    error: bad index file sha1 signature

While trying to track down the problem I noticed an error in my netbeans:

    java.nio.file.AccessDeniedException:
    .git/objects/29/21b847910981dd904c4281

This is the git object representing my .editorconfig file.

I tried it a several times and could reproduce it for this project when editorconfig is loaded/active in netbeans, activation status of git plugin did not make a difference.

Could this really be a problem inside the plugin? This is my system information:

```
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.8.0_45-internal; OpenJDK 64-Bit Server VM 25.45-b02
Runtime: OpenJDK Runtime Environment 1.8.0_45-internal-b14
System: Linux version 3.16.0-4-amd64 running on amd64; UTF-8; de_DE (nb)

editorconfig-netbeans 0.0.7.nbm
```

**Comment by t3dev** [comment] 2015-06-03 10:42
btw. rm .git/index does "fix" the problem.

**Comment by bennyn** [comment] 2015-06-03 11:46
Hi @t3dev,

Thanks for reporting this issue and the quick-fix for it. The EditorConfig plugin should ignore parsing the `.git` directory ([we are skipping it](https://github.com/welovecoding/editorconfig-netbeans/issues/76#issuecomment-108294689)). But it looks like that it isn't skipped in your case.

I will add some additional logging which could help us to track down the problem on your machine. Would be very happy if you can re-check it then!?

Best,
Benny

**Comment by t3dev** [comment] 2015-06-12 16:20
Hi Benny,
I would really like to assist you to get this out of the way. Until now I used your binary releases. Is there any pointer/hint on using this repo to build the plugin myself? I think I could maybe experiment with some debugs myself to tackle the problem.
I checked out the source but get lost on the way to turn this into a useful project in my netbeans installation that I could work with. Any help greatly appreciated.

**Comment by t3dev** [comment] 2015-06-14 18:30
added what I found in the README and created a pull request ;)

**Comment by bennyn** [comment] 2015-06-18 13:54
Hey @t3dev, thank you for your pull request! :+1:

But as the documentation for the EditorConfig plugin gets bigger and bigger we chose to add this information to our [Wiki](https://github.com/welovecoding/editorconfig-netbeans/wiki).

**Comment by t3dev** [comment] 2015-06-18 13:56
Hi Bennyn, sry for polluting this issue with unrelated stuff. The issue itself is still valid and a real blocker for the usage of the plugin. .git/index get's corrupted. :(

**Comment by bennyn** [comment] 2015-06-18 14:02
Uh, sorry. Then I was to eager closing this issue. Because you wrote:

> btw. rm .git/index does "fix" the problem.

So the problem is that the EditorConfig plugin is editing your `.git/index` file?

**Comment by t3dev** [comment] 2015-06-18 14:03
exactly! Which I consider to be a very serious issue...

**Comment by bennyn** [comment] 2015-06-18 14:13
Ok, labeled it with "high priority" ;)

**Comment by jscssphtml** [comment] 2015-07-23 14:16
I had a simmilar issue here with my node_modules directory - v0.0.7-beta.

And i'm thinking about what's going to happen if someone will change the bower_directory via .bowerrc file in a web project like:

{
  "directory": "vendor"
}

so that all vendor packages will download to "vendor" which is not the default. Can this be handeled by settings in .editorconf itsself?

**Comment by galeksandrp** [comment] 2015-08-27 01:15
Now is no exclude in `.editorconfig`. Workaround is adding `.editorconfig` to `vendor/` (or any other folder you need) with content `root = true;`

Or adding your folder here https://github.com/welovecoding/editorconfig-netbeans/blob/master/src/main/java/com/welovecoding/nbeditorconfig/processor/SmartSkip.java#L9

**Comment by bennyn** [comment] 2015-08-27 06:41
@t3dev Is the workaround mentioned by @galeksandrp a solution for you? I merged the solution from @galeksandrp a few minutes ago: https://github.com/welovecoding/editorconfig-netbeans/pull/85

**Closed** 2015-09-17 21:56 UTC
Labels: epic: Config Parser, flag: investigation, prio: high, type: bug
